# .devcontainer/Dockerfile
# Base image that allows features from devcontainer.json to be applied.
FROM mcr.microsoft.com/devcontainers/base:bullseye

# The 'command: sleep infinity' in docker-compose.yml for the 'app' service
# will keep the container running. Features like Python, Node, etc.,
# will be installed by Codespaces based on devcontainer.json.
